### ISSUE TITLE
Hero background image

### ISSUE THREAD

**Issue by ypxio** [MalangPHP/malang-devcamp-2016#2]
http://www.p-wec.org/sites/default/files/kampung-sumberbendo-dekat-pwec.jpg
http://media.halomalang.com/mediamanager/2012/03/Wisata/8/P-WEC/PWEC_(4).jpg
http://3.bp.blogspot.com/_Ysjp1LnAY4U/TUZueQVWctI/AAAAAAAABIo/FAWA765-G1E/s1600/IMG_0298.JPG

**Comment by ypxio** [comment]
saran: gambarnya 3 saja, masing2 mewakili :
1. Ikon kota Malang : https://shutterbugtravels.files.wordpress.com/2013/01/malang1.jpg
2. Ilustrasi camp : http://freetopwallpaper.com/wp-content/gallery/hd4/landscape-hd-wallpaper-free-202.jpg atau http://www.ymcatwincities.org/_asset/xlpr8w/primary_landing_camp.jpg atau http://www.coolwallpapers.org/photo/37688/Nature_Wallpapers_Landscape_Wallpapers-31.jpg
3. Foto meetup : ambil foto landscape wide d album meetup november 2015 (sing dibuat cover grup)

**Comment by praswicaksono** [comment]
budal no wes
